name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  build:
    strategy:
      matrix:
        go: ['1.22', '1']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test ./...
